version: '3'
services:
  nw-tools-backend:
    image: nw-tools-backend
    container_name: nw-tools-backend
    restart: always
    ports:
      - 3001:3001
    environment:
      - IPINFOIO_URL: https://ipinfo.io/
      - IPINFOIO_TOKEN: # your token
    