version: '3'
services:
  nw-tools-backend:
    image: nw-tools-backend
    container_name: symysak/nw-tools-backend:main
    restart: always
    ports:
     - 3001:3001
    environment:
     - IPINFOIO_API_URL="https://ipinfo.io/"
     - IPINFOIO_API_TOKEN="" # your token
    